version: '1.0'

networks:
  default:
    name: net-wallet

services:
  api-user:
    container_name: api-user
    build: ./api-user
    restart: always
    ports:
      - 3003:3003
    env_file:
      - ./api-user/.env

  api-saldo:
    container_name: api-saldo
    build: ./api-saldo
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ./api-saldo/.env

  api-extrato:
    container_name: api-extrato
    build: ./api-extrato
    restart: always
    ports:
      - 3002:3002
    env_file:
      - ./api-extrato/.env

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./api-gateway/.env

  client:
    container_name: client
    build: ./client
    depends_on:
      - api-user
      - api-saldo
      - api-extrato
      - api-gateway
    env_file:
      - ./client/.env
    volumes:
      - client-volume:/var/www/html

  nginx:
    container_name: nginx-wallet
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api-user
      - api-saldo
      - api-extrato
      - api-gateway
      - client

volumes:
  client-volume:
    name: client-volume